---
- name: Add Extra APT Repositories
  apt_repository: repo="{{ item }}"
  sudo: true
  with_items:
    - "{{extra_repos}}"

- name: Managing APT packages
  apt:
    state="{{ item.state }}"
    name="{{ item.name }}"
    update_cache=yes
  when: "ansible_system == 'Linux'"
  sudo: true
  with_items: apt_packages
