---
- name: Add Extra APT Repositories
  apt_repository: repo="{{ item }}"
  when: "ansible_system == 'Linux'"
  sudo: true
  with_items:
    - "{{extra_repos}}"
  tags:
    - apt
    - extra_repos

- name: Add APT Keys
  apt_key:
    keyserver={{ item.keyserver }}
    id={{ item.id }}
  sudo: true
  with_items: "{{ apt_keys }}"
  tags:
      - apt
      - apt_keys

- name: Managing APT packages
  apt:
    state="{{ item.state }}"
    name="{{ item.name }}"
    update_cache=yes
  when: "ansible_system == 'Linux'"
  sudo: true
  with_items: apt_packages
  tags:
    - apt
    - manage


