---
- name: Managing APT packages
  apt:
    state="{{ item.state }}"
    name="{{ item.name }}"
    update_cache=yes
    force=yes
  when: "ansible_system == 'Linux'"
  sudo: true
  with_items: apt_packages
  tags:
    - apt


