---

- name: Install dependencies
  apt: name={{ item }} state=installed update_cache=yes
  with_items: apt_packages

- name: Remove  dependencies
  apt: name={{ item }} state=absent update_cache=yes
  with_items: apt_remove_packages
